language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- RAILS_ENV=test bundle exec rails db:migrate --trace
- bundle exec rails db:test:prepare
- bundle exec rspec spec/
services:
- postgresql